import Head from "next/head";
import * as React from "react";
import Grid from "@mui/material/Grid";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Chip from "@mui/material/Chip";
import Stack from "@mui/material/Stack";
import { ThemeProvider } from "@mui/material/styles";
import { MainTheme } from "@/utils/MUITheme";

export default function projects() {
  return (
    <>
      <Head>
        <title>Mark Valentino</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThemeProvider theme={MainTheme}>
          <center>
            <Typography variant="h3" fontWeight={500} gutterBottom textTransform={"uppercase"}>
              Projects
            </Typography>
          </center>
          <Grid container justifyContent="center" spacing={4} direction="row">
            <Grid item>
              <Card sx={{ maxWidth: 345 }}>
                <CardContent>
                  <img
                    src="/citiesrecommender.png"
                    style={{ width: "100%" }}
                  ></img>
                  <Stack direction="row" spacing={1}>
                    <Typography variant="h6" color="primary">
                      2021
                    </Typography>
                    <Typography variant="h5">Cities Recommender</Typography>
                  </Stack>
                  <Typography variant="body2" color="text.secondary">
                    I wrote an AI program to recommend the best cities in
                    America to live in. Cities were optimized between being safe
                    and having favorable economic conditions (low cost of living
                    and high median income). Machine learning was used to
                    estimate unknown cost of living values of cities. Over 2000
                    cities were looked at.
                  </Typography>
                  <Stack direction="row" spacing={1} mt={1}>
                    <Chip label="Python" />
                    <Chip label="Java" />
                  </Stack>
                </CardContent>
              </Card>
            </Grid>
            <Grid item>
              <Card sx={{ maxWidth: 345 }}>
                <CardContent>
                  <img src="/calculator.jpg" style={{ width: "100%" }}></img>
                  <Stack direction="row" spacing={1}>
                    <Typography variant="h6" color="primary">
                      2022
                    </Typography>
                    <Typography variant="h5">Retro Calculator</Typography>
                  </Stack>
                  <Typography variant="body2" color="text.secondary">
                    A functional recreation of an old school style calculator
                    was made. I pushed CSS to the limit to make the calculator
                    photorealistic. Vector images were not used as I wanted to
                    make the calculator easier to be built upon in the future.
                    The entire webpage is very small and takes up 14Kb.
                  </Typography>
                  <Stack direction="row" spacing={1} mt={1}>
                    <Chip label="JS" />
                    <Chip label="CSS" />
                    <Chip label="HTML5" />
                  </Stack>
                </CardContent>
              </Card>
            </Grid>
          </Grid>
        </ThemeProvider>
      </main>
    </>
  );
}
