import Head from "next/head";
import * as React from "react";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Chip from '@mui/material/Chip';
import Stack from '@mui/material/Stack';

export default function projects() {
  return (
    <>
      <Head>
        <title>Mark Valentino</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Card sx={{ maxWidth: 345 }}>
          <CardContent>
          <img src="/citiesrecommender.png" style={{width: "100%"}}></img>
            <Typography gutterBottom variant="h5" component="div">
              Cities Recommender
            </Typography>
            <Typography variant="body2" color="text.secondary">
              I wrote an AI program to recommend the best cities in America to
              live in. Cities were optimized between being safe and having
              favorable economic conditions (low cost of living and high median
              income). Machine learning was used to estimate unknown cost of
              living values of cities. Over 2000 cities were looked at.
            </Typography>
            <Stack direction="row" spacing={1}>
              <Chip label="Python" />
              <Chip label="Java" />
            </Stack>
          </CardContent>
        </Card>
      </main>
    </>
  );
}
